name: flutter_chat_app
description: A Flutter project with chat interacting with API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.6.1'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter